const colors = {
  amber: 'amber',
  black: 'black',
  blue: 'blue',
  blueGray: 'blueGray',
  cyan: 'cyan',
  emerald: 'emerald',
  fuchsia: 'fuchsia',
  gray: 'gray',
  green: 'green',
  indigo: 'indigo',
  lightBlue: 'lightBlue',
  lime: 'lime',
  orange: 'orange',
  pink: 'pink',
  primary: 'primary',
  purple: 'purple',
  red: 'red',
  rose: 'rose',
  teal: 'teal',
  transparent: 'transparent',
  violet: 'violet',
  yellow: 'yellow',
  white: 'white',
};

export type Colors = typeof colors;
export type ColorsType = keyof typeof colors;
export const ColorsMap: { [key in ColorsType]: ColorsType } = {
  amber: 'amber',
  black: 'black',
  blue: 'blue',
  blueGray: 'blueGray',
  cyan: 'cyan',
  emerald: 'emerald',
  fuchsia: 'fuchsia',
  gray: 'gray',
  green: 'green',
  indigo: 'indigo',
  lightBlue: 'lightBlue',
  lime: 'lime',
  orange: 'orange',
  pink: 'pink',
  primary: 'primary',
  purple: 'purple',
  red: 'red',
  rose: 'rose',
  teal: 'teal',
  transparent: 'transparent',
  violet: 'violet',
  yellow: 'yellow',
  white: 'white',
};
