-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.delete_account(
	id uuid)
    RETURNS SETOF "creditCard" 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
begin
  if exists(select 1 from transaction where "accountId" = id) then
    update "account"
    set "archivedAt" = now()
    where "accountId" = id
    returning *;
  else
    delete from "account"
    where "accountId" = id
    returning *;
  end if;
end;
$BODY$;

ALTER FUNCTION public.delete_account(uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.delete_creditcard(
	id uuid)
    RETURNS SETOF "creditCard" 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
begin
  if exists(select 1 from transaction where "creditCardId" = id) then
    update "creditCard"
    set "archivedAt" = now()
    where "creditCardId" = id
    returning *;
  else
    delete from "creditCard"
    where "creditCardId" = id
    returning *;
  end if;
end;
$BODY$;

ALTER FUNCTION public.delete_creditcard(uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO service_role;
