-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: creditCardType

-- DROP TYPE IF EXISTS public."creditCardType";

CREATE TYPE public."creditCardType" AS ENUM
    ('amex', 'carrefour', 'mastercard', 'naranja', 'visa');

ALTER TYPE public."creditCardType"
    OWNER TO postgres;

-- Type: currency

-- DROP TYPE IF EXISTS public.currency;

CREATE TYPE public.currency AS ENUM
    ('ars', 'usd');

ALTER TYPE public.currency
    OWNER TO postgres;

-- Type: movementType

-- DROP TYPE IF EXISTS public."movementType";

CREATE TYPE public."movementType" AS ENUM
    ('expenses', 'incomes', 'investment', 'transfer');

ALTER TYPE public."movementType"
    OWNER TO postgres;

-- Type: accountType

-- DROP TYPE IF EXISTS public."accountType";

CREATE TYPE public."accountType" AS ENUM
    ('bank', 'cash');

ALTER TYPE public."accountType"
    OWNER TO postgres;

-- Type: investmentType

-- DROP TYPE IF EXISTS public."investmentType";

CREATE TYPE public."investmentType" AS ENUM
    ('fci', 'fixed', 'uva');

ALTER TYPE public."investmentType"
    OWNER TO postgres;

-- Type: quotationType

-- DROP TYPE IF EXISTS public."quotationType";

CREATE TYPE public."quotationType" AS ENUM
    ('blue', 'mep', 'ccl', 'usd', 'usd+');

ALTER TYPE public."quotationType"
    OWNER TO postgres;
