-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.transfer
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "sourceMovementId" uuid NOT NULL,
    "destinationMovementId" uuid NOT NULL,
    "quotationAmount" numeric(11,4),
    "userId" uuid NOT NULL,
    CONSTRAINT transfer_pkey PRIMARY KEY (id),
    CONSTRAINT "fk_movement_destinationMovement" FOREIGN KEY ("destinationMovementId")
        REFERENCES public.movement (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_movement_sourceMovement" FOREIGN KEY ("sourceMovementId")
        REFERENCES public.movement (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_transfer_user FOREIGN KEY ("userId")
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.transfer
    OWNER to postgres;

ALTER TABLE IF EXISTS public.transfer
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.transfer TO anon;

GRANT ALL ON TABLE public.transfer TO authenticated;

GRANT ALL ON TABLE public.transfer TO postgres;

GRANT ALL ON TABLE public.transfer TO service_role;
CREATE POLICY "Users can delete their own transfers."
    ON public.transfer
    AS PERMISSIVE
    FOR DELETE
    TO public
    USING ((auth.uid() = "userId"));
CREATE POLICY "Users can insert their own transfers."
    ON public.transfer
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Users can update their own transfers."
    ON public.transfer
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = "userId"));
CREATE POLICY "Users can view their own transfers."
    ON public.transfer
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = "userId"));

