-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.investment
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    description character varying(100) COLLATE pg_catalog."default" NOT NULL,
    type "investmentType" NOT NULL,
    "accountId" uuid NOT NULL,
    amount numeric(11,4) NOT NULL,
    days smallint,
    "dueDate" timestamp without time zone,
    "annualRate" numeric(11,4),
    profit numeric(11,4),
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "userId" uuid NOT NULL,
    CONSTRAINT investment_pkey PRIMARY KEY (id),
    CONSTRAINT fk_investment_account FOREIGN KEY ("accountId")
        REFERENCES public.account (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_investment_user FOREIGN KEY ("userId")
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.investment
    OWNER to postgres;

ALTER TABLE IF EXISTS public.investment
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.investment TO anon;

GRANT ALL ON TABLE public.investment TO authenticated;

GRANT ALL ON TABLE public.investment TO postgres;

GRANT ALL ON TABLE public.investment TO service_role;
CREATE POLICY "Users can delete their own investments."
    ON public.investment
    AS PERMISSIVE
    FOR DELETE
    TO public
    USING ((auth.uid() = "userId"));
CREATE POLICY "Users can insert their own investments."
    ON public.investment
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Users can update their own investments."
    ON public.investment
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = "userId"));
CREATE POLICY "Users can view their own investments."
    ON public.investment
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = "userId"));
