-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.get_balance(IN "accId" uuid,IN "endDate" timestamp without time zone)
    RETURNS TABLE(amount numeric, date timestamp without time zone)
    LANGUAGE 'sql'
    VOLATILE
    PARALLEL UNSAFE
    COST 100    ROWS 1000 
    
AS $BODY$

  with cte as (
    select 
      case
          -- when t.is_paid = false then 0
        when type = 'expenses' then amount * (-1)
        when type = 'incomes' then amount
        else 0
      end as amount
    from public.transaction as t
      left join public.get_ocurrences(t.id) as o
        on o.id = t.id and o.date <= "endDate"
    where
      t."accountId" = "accId"
      and (
            ( o.date is not null and o.date <= "endDate" ) or 
            ( o.date is null and t.date <= "endDate" )
          )
    union all
    select 
      "initialAmount" as amount
    from "account" as a
    where a.id = "accId"
  )
  select
    SUM(amount) as amount,
    date_trunc('month', "endDate") + interval '1 month' as date
  from cte;

$BODY$;
