-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.get_totals_by_category(
	"startDate" timestamp without time zone,
	"endDate" timestamp without time zone)
    RETURNS TABLE(type "transactionType", "rootCategoryId" uuid, "rootCategory" character varying, "rootCategoryColor" character varying, "rootCategoryIcon" character varying, "subCategoryId" uuid, "subCategory" character varying, amount numeric)
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$

select
  t.type,
  coalesce("parentCat".id, cat.id) as "rootCategoryId",
  coalesce("parentCat".name, cat.name) as "rootCategory",
  coalesce("parentCat".color, cat.color) as "rootCategoryColor",
  coalesce("parentCat".icon, cat.icon) as "rootCategoryIcon",
  case when "parentCat".id is null then null else cat.id end as "subCategoryId",
  case when "parentCat".id is null then null else cat.name end as "subCategory",
  SUM(t.amount) as total
from transaction as t
  inner join category as cat
    on t."categoryId" = cat.id
  left join category as "parentCat"
    on cat."parentId" = "parentCat".id

  left join public.get_ocurrences(t.id) as o
      on o.id = t.id and o.date >= "startDate" and o.date <= "endDate"

where  COALESCE(o.date, t.date) >= "startDate"
    and COALESCE(o.date, t.date) <= "endDate"
group by
  t.type,
  "parentCat".id,
  cat.id,
  "parentCat".name,
  cat.name,
  "parentCat".color,
  cat.color,
  "parentCat".icon,
  cat.icon

$BODY$;

ALTER FUNCTION public.get_totals_by_category(timestamp without time zone, timestamp without time zone)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.get_totals_by_category(timestamp without time zone, timestamp without time zone) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.get_totals_by_category(timestamp without time zone, timestamp without time zone) TO anon;

GRANT EXECUTE ON FUNCTION public.get_totals_by_category(timestamp without time zone, timestamp without time zone) TO authenticated;

GRANT EXECUTE ON FUNCTION public.get_totals_by_category(timestamp without time zone, timestamp without time zone) TO postgres;

GRANT EXECUTE ON FUNCTION public.get_totals_by_category(timestamp without time zone, timestamp without time zone) TO service_role;
