-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
-- DROP TYPE IF EXISTS public.currency;

-- Type: currency
CREATE TYPE public.currency AS ENUM
    ('ars', 'usd');

ALTER TABLE IF EXISTS public.account
    ADD COLUMN currency currency NOT NULL DEFAULT 'ars'::currency;

ALTER TYPE public.currency
    OWNER TO postgres;
