-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.delete_account(
	id uuid)
    RETURNS SETOF "account"
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000
AS $BODY$
DECLARE
  _id uuid = id;
begin
  if exists(select 1 from transaction where "accountId" = _id) then
    return query (
      with cte as (
        update "account" as a
        set "archivedAt" = now()
        where a."id" = _id
        returning *
      )
      select *
      from cte
    );
  else
    return query (
      with cte as (
        delete from "account" as a
        where a."id" = _id
        returning *
      )
      select *
      from cte
    );
  end if;

  return;
end;
$BODY$;

ALTER FUNCTION public.delete_account(uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_account(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.delete_creditcard(
	id uuid)
    RETURNS SETOF "creditCard"
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000
AS $BODY$
DECLARE
  _id uuid = id;
begin
  if exists(select 1 from transaction where "creditCardId" = _id) then
    return query (
      with cte as (
        update "creditCard" as cc
        set "archivedAt" = now()
        where cc."id" = _id
        returning *
      )
      select *
      from cte
    );
  else
    return query (
      with cte as (
        delete from "creditCard" as cc
        where cc."id" = _id
        returning *
      )
      select *
      from cte
    );
  end if;

  return;
end;
$BODY$;

ALTER FUNCTION public.delete_creditcard(uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.delete_creditcard(uuid) TO service_role;
