-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."movementFee"
(
    id uuid NOT NULL,
    "bucketId" uuid NOT NULL,
    "feeNumber" smallint NOT NULL,
    "totalFees" smallint NOT NULL,
    CONSTRAINT "movementFee_pkey" PRIMARY KEY (id),
    CONSTRAINT "fk_movement_movementFee" FOREIGN KEY (id)
        REFERENCES public.movement (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."movementFee"
    OWNER to postgres;

GRANT ALL ON TABLE public."movementFee" TO anon;

GRANT ALL ON TABLE public."movementFee" TO authenticated;

GRANT ALL ON TABLE public."movementFee" TO postgres;

GRANT ALL ON TABLE public."movementFee" TO service_role;
