-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public."getPriorBalance"(
	"pAccountId" uuid,
	"pCurrentMonth" smallint,
	"pCurrentYear" smallint)
    RETURNS TABLE(amount numeric, "investmentAmount" numeric)
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$

  select
    SUM(m.amount) as amount,
    SUM(case when m."investmentId" is not null then m.amount * -1 else 0 end) as "investmentAmount"
  from public.movement as m
  where
    (
      (m.year = "pCurrentYear" and m.month < "pCurrentMonth") or (m.year < "pCurrentYear")
    )
    and ("pAccountId" is null or m."accountId" = "pAccountId")

$BODY$;

ALTER FUNCTION public."getPriorBalance"(uuid, smallint, smallint)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public."getPriorBalance"(uuid, smallint, smallint) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."getPriorBalance"(uuid, smallint, smallint) TO anon;

GRANT EXECUTE ON FUNCTION public."getPriorBalance"(uuid, smallint, smallint) TO authenticated;

GRANT EXECUTE ON FUNCTION public."getPriorBalance"(uuid, smallint, smallint) TO postgres;

GRANT EXECUTE ON FUNCTION public."getPriorBalance"(uuid, smallint, smallint) TO service_role;
